<a href="https://colab.research.google.com/github/okada-t-rafael/pytorch_study/blob/master/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [2]:
# Details of gpu, if a gpu is active.
!nvidia-smi

Tue Aug 22 13:18:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()`: https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
s = torch.tensor(7)
s

tensor(7)

In [4]:
s.ndim

0

In [5]:
# Get tensor back as python int
s.item()

7

In [6]:
# Vector
v = torch.tensor([7, 7])
v

tensor([7, 7])

In [7]:
v.ndim

1

In [8]:
v.shape

torch.Size([2])

In [9]:
# Matrix
M = torch.tensor(
    [[7, 8],
     [9, 10]])
M

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
M.ndim

2

In [11]:
M[0]

tensor([7, 8])

In [12]:
M.shape

torch.Size([2, 2])

In [13]:
# Tensor
T = torch.tensor(
    [[[1, 2, 3],
      [3, 6, 9],
      [2, 4, 5]]])
T

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
T.ndim

3

In [15]:
T.shape

torch.Size([1, 3, 3])

In [16]:
T[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
T[0][1]

tensor([3, 6, 9])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is what they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2773, 0.3474, 0.2419, 0.8733],
        [0.2342, 0.4264, 0.5299, 0.5873],
        [0.6105, 0.7339, 0.2038, 0.3019]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))  # colour channel(r, g, b), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [22]:
random_image_size_tensor

tensor([[[0.1485, 0.3226, 0.7466,  ..., 0.1261, 0.4893, 0.5608],
         [0.8334, 0.2992, 0.3957,  ..., 0.3726, 0.9022, 0.7834],
         [0.0673, 0.8113, 0.0769,  ..., 0.8702, 0.3757, 0.4929],
         ...,
         [0.9017, 0.3764, 0.8839,  ..., 0.1292, 0.3467, 0.1417],
         [0.5556, 0.0160, 0.9173,  ..., 0.9419, 0.9127, 0.3436],
         [0.0494, 0.5487, 0.9391,  ..., 0.5630, 0.8873, 0.9283]],

        [[0.1077, 0.2117, 0.8111,  ..., 0.6583, 0.7140, 0.3640],
         [0.5981, 0.8312, 0.9249,  ..., 0.3088, 0.4084, 0.4076],
         [0.6214, 0.2211, 0.6730,  ..., 0.6038, 0.6403, 0.9782],
         ...,
         [0.5853, 0.5149, 0.8882,  ..., 0.3339, 0.6938, 0.2059],
         [0.8923, 0.3470, 0.9514,  ..., 0.1189, 0.6039, 0.0199],
         [0.7972, 0.8347, 0.0442,  ..., 0.9142, 0.2010, 0.9255]],

        [[0.2777, 0.8469, 0.6285,  ..., 0.8703, 0.5525, 0.0201],
         [0.4768, 0.4643, 0.1156,  ..., 0.1376, 0.9446, 0.4736],
         [0.2542, 0.7666, 0.6223,  ..., 0.2240, 0.1750, 0.

### Zero and Ones

In [23]:
# Create a tensor of all zeros
zeroes = torch.zeros(size=(3, 4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [27]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [28]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [29]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (e.g. float32 or float16)
                               device=None,  # what device is your tensor on (e.g. cpu or cuda)
                               requires_grad=False)  # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can user `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [34]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3420, 0.1622, 0.1582, 0.0323],
        [0.7758, 0.9675, 0.6065, 0.8448],
        [0.0729, 0.4430, 0.0389, 0.8500]])

In [35]:
# Find out details about some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [39]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [40]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [41]:
%%time
tensor * 10

CPU times: user 74 µs, sys: 12 µs, total: 86 µs
Wall time: 89.6 µs


tensor([10, 20, 30])

In [42]:
%%time
torch.mul(tensor, 10)

CPU times: user 512 µs, sys: 0 ns, total: 512 µs
Wall time: 435 µs


tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matricees - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [43]:
# Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 487 µs, sys: 73 µs, total: 560 µs
Wall time: 568 µs


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 99 µs, sys: 0 ns, total: 99 µs
Wall time: 104 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [49]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)  # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape isses, we can manipuate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [51]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [52]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [53]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [54]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match


In [55]:
print("Output:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [56]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [57]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [58]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
# Find the mean
torch.mean(x)

RuntimeError: ignored

In [60]:
# Find the mean - note: the torch.mean() function requries a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Findig the positional min and max

In [62]:
another_x = torch.rand(10)
another_x

tensor([0.4999, 0.7115, 0.4558, 0.2014, 0.4600, 0.7495, 0.6876, 0.2707, 0.7800,
        0.7249])

In [63]:
# Finding the position in tensor that has the minimum value with argmin() -> return index position of target tensor where the minimum value occurs
another_x.argmin()

tensor(3)

In [64]:
another_x[5]

tensor(0.7495)

In [65]:
# Find the position in tensor that has the maximum value with argmax()
another_x.argmax()

tensor(8)

In [66]:
another_x[0]

tensor(0.4999)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstrack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [67]:
# Let's create a tensor
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [68]:
# Add an extra dimension
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [69]:
# Change the view
z = x.view(2, 5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [70]:
# Changin z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = -99
z, x

(tensor([[-99.,   2.,   3.,   4.,   5.],
         [-99.,   7.,   8.,   9.,  10.]]),
 tensor([-99.,   2.,   3.,   4.,   5., -99.,   7.,   8.,   9.,  10.]))

In [71]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x], dim=0)
x_stacked

tensor([[-99.,   2.,   3.,   4.,   5., -99.,   7.,   8.,   9.,  10.],
        [-99.,   2.,   3.,   4.,   5., -99.,   7.,   8.,   9.,  10.]])

In [72]:
x_stacked = torch.stack([x, x], dim=1)
x_stacked

tensor([[-99., -99.],
        [  2.,   2.],
        [  3.,   3.],
        [  4.,   4.],
        [  5.,   5.],
        [-99., -99.],
        [  7.,   7.],
        [  8.,   8.],
        [  9.,   9.],
        [ 10.,  10.]])

In [73]:
# torch.squeeze() - remove all single dimensions from a target tensor
x = torch.arange(1., 11.)
x = x.reshape(1, 10)
print(f"Previous tensor: {x}")
print(f"Previous shape: {x.shape}")

# Remove extra dimensions from x
x_squeezed = x.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
New shape: torch.Size([10])


In [74]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

# Add an extra dimension to dim=1
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])

New tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape: torch.Size([1, 10])

New tensor: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [75]:
# torch.permute - rearranges the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))  # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [76]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [77]:
# Let's index with our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [79]:
x[0, 0]

tensor([1, 2, 3])

In [80]:
# Let's index on the most inner bracket (last dim)
x[0][0][0]

tensor(1)

In [81]:
x[0, 2, 2]

tensor(9)

In [82]:
# You can also use ":" to select "all" of a target dimension
x[0, :, 0]

tensor([1, 4, 7])

In [83]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [84]:
# Get all values of the 0 dimensions but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [85]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [86]:
# Index on x to return on 9
x[0, 2, 2]

tensor(9)

In [87]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functinality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [88]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
array.dtype

dtype('float64')

In [90]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [91]:
# Change the value of array, what will this do to `tensor`?
array[0] = -99
array, tensor

(array([-99.,   2.,   3.,   4.,   5.,   6.,   7.]),
 tensor([-99.,   2.,   3.,   4.,   5.,   6.,   7.], dtype=torch.float64))

In [92]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [93]:
# Change the tensor, what happens to `numpy_tensor`?
tensor[0] = -99
tensor, numpy_tensor

(tensor([-99.,   1.,   1.,   1.,   1.,   1.,   1.]),
 array([-99.,   1.,   1.,   1.,   1.,   1.,   1.], dtype=float32))

## Reproducebility (trying to take random out of random)

In short how a neural network learns:

`starts with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [94]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3533, 0.6755, 0.1665, 0.3721],
        [0.4465, 0.9768, 0.0764, 0.7099],
        [0.8058, 0.3098, 0.2244, 0.0568]])
tensor([[0.8223, 0.6657, 0.4057, 0.0557],
        [0.3128, 0.3817, 0.6011, 0.8019],
        [0.4699, 0.9662, 0.1646, 0.0360]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [95]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hnky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (Options to upgrade as well)
2. Use our own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [96]:
!nvidia-smi

Tue Aug 22 13:21:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [97]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since it's capable of running on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU.

In [98]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [99]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [102]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [103]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [104]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [106]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy()

array([1, 2, 3])

In [107]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum