<a href="https://colab.research.google.com/github/okada-t-rafael/pytorch_study/blob/master/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises

In [1]:
import torch

## Exercise 1
Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

Links:
- https://pytorch.org/docs/stable/tensors.html#torch-tensor
- https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics



## Exercise 2
Create a random tensor with shape (7, 7)

In [2]:
T1 = torch.rand(size=[7, 7])
T1, T1.shape

(tensor([[0.1761, 0.7398, 0.0485, 0.7755, 0.9142, 0.2175, 0.6356],
         [0.8415, 0.2794, 0.3137, 0.9097, 0.3895, 0.3439, 0.6869],
         [0.2160, 0.4783, 0.0676, 0.2840, 0.1504, 0.0892, 0.9865],
         [0.8032, 0.5110, 0.0812, 0.2007, 0.9463, 0.1479, 0.3696],
         [0.2969, 0.0539, 0.2848, 0.2260, 0.8902, 0.1545, 0.0258],
         [0.9443, 0.5283, 0.0631, 0.4685, 0.2048, 0.5542, 0.6388],
         [0.8140, 0.4064, 0.4665, 0.5976, 0.6965, 0.8755, 0.8181]]),
 torch.Size([7, 7]))

## Exercise 3
Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to tranpose the second tensor).

In [3]:
T2 = torch.rand(size=[1, 7])
T2

tensor([[0.2453, 0.3659, 0.7740, 0.4874, 0.2587, 0.4028, 0.7038]])

In [4]:
T3 = torch.matmul(T1, T2.T)
T3

tensor([[1.5010],
        [1.7176],
        [1.1878],
        [1.1092],
        [0.7338],
        [1.4279],
        [2.1093]])

## Exercise 4
Set the random seed to 0 and do exercises 2 & 3 again.

In [5]:
torch.manual_seed(0)
T1_new = torch.rand(size=[7, 7])
T1_new

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [6]:
torch.manual_seed(0)
T2_new = torch.rand(size=[1, 7])
T2_new

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [7]:
T3_new = torch.matmul(T1_new, T2_new.T)
T3_new

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

## Exercise 5
Speaking of random seeds, we saw hot to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [8]:
!nvidia-smi

Mon Aug 28 23:24:58 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [9]:
torch.cuda.is_available()

True

In [10]:
torch.cuda.manual_seed(1234)
T4 = torch.rand(size=[1, 7], device="cuda")
T4

tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903]],
       device='cuda:0')

# Exercise 6
Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doens't have to be the GPU random seed).

In [11]:
torch.manual_seed(1234)
T5 = torch.rand(2, 3)
T6 = torch.rand(2, 3)

In [12]:
T7 = T5.to("cuda")
T8 = T6.to("cuda")
T7, T8

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

# Exercise 7
Perform a matrix multiplication on the tensors you create in 6 (again, you may have to adjust the shapes of one of the tensors).

In [13]:
T9 = torch.matmul(T7, T8.T)
T9

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

# Exercise 8
Find the maximum and minimum values of the output of 7.

In [14]:
torch.max(T9), torch.min(T9)

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

# Exercise 9
Find the maximum and minimum index values of the output of 7.

In [15]:
torch.argmax(T9), torch.argmin(T9)

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

# Exercise 10
Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [16]:
torch.manual_seed(7)
T10 = torch.rand(size=[1, 1, 1, 10])
T10, T10.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [17]:
T11 = T10.squeeze()
T11, T11.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))